import { describe, expect, it } from "vitest";

describe("BIS adapter contract", () => {
  it("uses the documented WS_SPP dataflow and SDMX JSON negotiation", async () => {
    const source = "import type { EvidenceObservation } from \"../types\";\n\nconst BIS_BASE = \"https://stats.bis.org/api/v2/data/dataflow/BIS/WS_SPP/1.0\";\n\ntype Dimension = { id: string; values: Array<{ id: string; name?: string }> };\ntype Sdmx = {\n  data?: {\n    structure?: { dimensions?: { series?: Dimension[]; observation?: Dimension[] } };\n    dataSets?: Array<{ series?: Record<string, { observations?: Record<string, number[]> }> }>;\n  };\n};\n\nfunction quarterStart(period: string): string | null {\n  const m = /^(\\d{4})-Q([1-4])$/.exec(period);\n  return m ? m[1] + \"-\" + String((Number(m[2]) - 1) * 3 + 1).padStart(2, \"0\") + \"-01T00:00:00.000Z\" : null;\n}\n\nfunction parseBIS(dataset: Sdmx, requestedGeos: string[]) {\n  const structure = dataset.data?.structure;\n  const seriesDimensions = structure?.dimensions?.series ?? [];\n  const observationDimensions = structure?.dimensions?.observation ?? [];\n  const rawSeries = dataset.data?.dataSets?.[0]?.series ?? {};\n  const timeDimension = observationDimensions.find((d) => d.id === \"TIME_PERIOD\");\n  const timeValues = timeDimension?.values ?? [];\n  const geoIndex = seriesDimensions.findIndex((d) => d.id === \"REF_AREA\");\n  const measureIndex = seriesDimensions.findIndex((d) => d.id === \"VALUE_MEASURE\");\n  const rows: Array<{ geo: string; measure: string; period: string; value: number }> = [];\n\n  for (const [seriesKey, seriesData] of Object.entries(rawSeries)) {\n    const indices = seriesKey.split(\":\").map(Number);\n    const geo = seriesDimensions[geoIndex]?.values[indices[geoIndex] ?? -1]?.id;\n    const measure = measureIndex >= 0 ? seriesDimensions[measureIndex]?.values[indices[measureIndex] ?? -1]?.id ?? \"\" : \"\";\n    if (!geo || (requestedGeos.length && !requestedGeos.includes(geo))) continue;\n    for (const [obsKey, payload] of Object.entries(seriesData.observations ?? {})) {\n      const timeIndex = Number(obsKey.split(\":\")[0]);\n      const period = timeValues[timeIndex]?.id;\n      const value = payload[0];\n      if (!period || typeof value !== \"number\" || !Number.isFinite(value)) continue;\n      rows.push({ geo, measure, period, value });\n    }\n  }\n  return rows;\n}\n";
    expect(source).toContain("WS_SPP");
    expect(source).toContain("application/vnd.sdmx.data+json");
    expect(source).toContain('const key = "Q."');
    expect(source).toContain('." + measures.join("+")');
  });
});
