// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createNoopSupabaseClient() {
  const noopPromise = async () => ({ data: null, error: null });
  const noopQueryBuilder = () => ({
    select: () => noopQueryBuilder(),
    eq: () => noopQueryBuilder(),
    order: () => noopQueryBuilder(),
    limit: () => noopQueryBuilder(),
    async maybeSingle() {
      return { data: null, error: null };
    },
    async single() {
      return { data: null, error: null };
    },
    async insert() {
      return { data: null, error: null };
    },
    async update() {
      return { data: null, error: null };
    },
    async delete() {
      return { data: null, error: null };
    },
    async upsert() {
      return { data: null, error: null };
    },
    async then() {
      return { data: null, error: null };
    },
  });

  return {
    auth: {
      async getSession() {
        return { data: { session: null }, error: null };
      },
      onAuthStateChange() {
        return {
          data: {
            subscription: { unsubscribe() {} },
          },
          error: null,
        };
      },
      async signOut() {
        return { error: null };
      },
      async signInWithPassword() {
        return { data: { session: null, user: null }, error: null };
      },
      async signUp() {
        return { data: { session: null, user: null }, error: null };
      },
    },
    from: () => noopQueryBuilder(),
    rpc: noopPromise,
    channel: () => ({
      on: () => ({
        subscribe: () => ({ unsubscribe() {} }),
      }),
    }),
    functions: {
      async invoke() {
        return { data: null, error: null };
      },
    },
  } as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.warn(`[Supabase] ${message} Falling back to a safe no-op client so the app can still render.`);
    return createNoopSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
